Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,9 +1,8 @@
 name: CI/CD GreenCityUser
-# Controls when the action will run. 
+
 concurrency: Testing
 
 on:
-  # Triggers the workflow on push or pull request events but only for the master branch
   push:
     branches: [ master, dev ]
   pull_request:
@@ -14,17 +13,14 @@ env:
   repository: user
   userRepoName: core
   onbootJarName: app.jar
-  dockerRepoName: skyere/greencityuser
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
     runs-on: ubuntu-latest
     permissions:
       checks: write
       contents: read
-    # Steps represent a sequence of tasks that will be executed as part of the job
+
     steps:
       - uses: actions/checkout@v3
 
@@ -34,7 +30,7 @@ jobs:
           distribution: 'temurin'
           java-version: 21
 
-      - name: Run a multi-line script
+      - name: Build, test & run Sonar
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -45,9 +41,9 @@ jobs:
             -Dsonar.organization=greencity-ua-4146-4625-01 \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.sources=src/main/java/greencity \
-            -Dsonar.binaries=target/classes
-        # Checks-out your greencity.repository under $GITHUB_WORKSPACE, so your job can access it
-      
+            -Dsonar.binaries=target/classes \
+            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+
       - name: Test Reporter
         uses: dorny/test-reporter@v1.5.0
         if: success() || failure()
@@ -55,43 +51,12 @@ jobs:
           name: Tests Report
           path: "**/target/surefire-reports/*.xml"
           reporter: java-junit
-      
+
       - name: Rename user jar to app
         run: mv $userRepoName/target/*.jar $userRepoName/target/$onbootJarName
 
-      - name: Set outputs
+      - name: Set short SHA for further steps
         run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
-
-      - name: Docker Login
-        uses: docker/login-action@v2.0.0
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Build and push Docker images
-        uses: docker/build-push-action@v3.0.0
-        with:
-          context: .
-          file: Dockerfile
-          push: true
-          tags: ${{ env.dockerRepoName }}:test-${{ env.GITHUB_SHA_SHORT }}
-      
-#       - name: Kubernetes Set Context
-#         uses: Azure/k8s-set-context@v3.0
-#         with:
-#           kubeconfig: ${{ secrets.KUBE_CONFIG }}
-      
-#       - name: Set up Postgres
-#         run: kubectl scale deploy postgres --replicas=1 -n test
-      
-#       - name: Kubernetes tests
-#         run: |
-#           cd chart-test
-#           go test -v ./...
-      
-#       - name: Post Set up Postgres
-#         if: success() || failure()
-#         run: kubectl scale deploy postgres --replicas=0 -n test
 
       - name: Deploy 🚀
         if: ${{ github.event_name == 'push' }}
@@ -100,4 +65,109 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           BRANCH: gh-pages
           FOLDER: .
-          CLEAN: true 
+          CLEAN: true
+
+
+# name: CI/CD GreenCityUser
+# # Controls when the action will run. 
+# concurrency: Testing
+
+# on:
+#   # Triggers the workflow on push or pull request events but only for the master branch
+#   push:
+#     branches: [ master, dev ]
+#   pull_request:
+#     branches: [ master, dev ]
+#   workflow_dispatch:
+
+# env:
+#   repository: user
+#   userRepoName: core
+#   onbootJarName: app.jar
+#   dockerRepoName: skyere/greencityuser
+
+# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
+# jobs:
+#   # This workflow contains a single job called "build"
+#   build:
+#     runs-on: ubuntu-latest
+#     permissions:
+#       checks: write
+#       contents: read
+#     # Steps represent a sequence of tasks that will be executed as part of the job
+#     steps:
+#       - uses: actions/checkout@v3
+
+#       - name: Set up JDK 21
+#         uses: actions/setup-java@v3
+#         with:
+#           distribution: 'temurin'
+#           java-version: 21
+
+#       - name: Run a multi-line script
+#         env:
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#         run: |
+#           git fetch --unshallow || true
+#           mvn clean verify sonar:sonar \
+#             -Dsonar.projectKey=GreenCity-UA-4146-4625-01_GreenCityUser21 \
+#             -Dsonar.organization=greencity-ua-4146-4625-01 \
+#             -Dsonar.host.url=https://sonarcloud.io \
+#             -Dsonar.sources=src/main/java/greencity \
+#             -Dsonar.binaries=target/classes
+#         # Checks-out your greencity.repository under $GITHUB_WORKSPACE, so your job can access it
+      
+#       - name: Test Reporter
+#         uses: dorny/test-reporter@v1.5.0
+#         if: success() || failure()
+#         with:
+#           name: Tests Report
+#           path: "**/target/surefire-reports/*.xml"
+#           reporter: java-junit
+      
+#       - name: Rename user jar to app
+#         run: mv $userRepoName/target/*.jar $userRepoName/target/$onbootJarName
+
+#       - name: Set outputs
+#         run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+
+#       - name: Docker Login
+#         uses: docker/login-action@v2.0.0
+#         with:
+#           username: ${{ secrets.DOCKERHUB_USERNAME }}
+#           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+#       - name: Build and push Docker images
+#         uses: docker/build-push-action@v3.0.0
+#         with:
+#           context: .
+#           file: Dockerfile
+#           push: true
+#           tags: ${{ env.dockerRepoName }}:test-${{ env.GITHUB_SHA_SHORT }}
+      
+# #       - name: Kubernetes Set Context
+# #         uses: Azure/k8s-set-context@v3.0
+# #         with:
+# #           kubeconfig: ${{ secrets.KUBE_CONFIG }}
+      
+# #       - name: Set up Postgres
+# #         run: kubectl scale deploy postgres --replicas=1 -n test
+      
+# #       - name: Kubernetes tests
+# #         run: |
+# #           cd chart-test
+# #           go test -v ./...
+      
+# #       - name: Post Set up Postgres
+# #         if: success() || failure()
+# #         run: kubectl scale deploy postgres --replicas=0 -n test
+
+#       - name: Deploy 🚀
+#         if: ${{ github.event_name == 'push' }}
+#         uses: JamesIves/github-pages-deploy-action@3.7.1
+#         with:
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#           BRANCH: gh-pages
+#           FOLDER: .
+#           CLEAN: true 
